//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiganshinaMilana_Matie_WPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int ServiceId { get; set; }
        public int MasterId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> QueueNumber { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Master Master { get; set; }
        public virtual Service Service { get; set; }
        public virtual AppointmentStatus AppointmentStatus { get; set; }
    }
}
