//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiganshinaMilana_Matie_WPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationUpgradeRequest
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string CurrentQualification { get; set; }
        public int StatusId { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual QualificationUpgradeRequestStatus QualificationUpgradeRequestStatus { get; set; }
    }
}
